export const formFields = {
  fullName: {
    label: "Nombre Completo",
    name: "fullName",
    type: "text",
    required: true,
    icon: <i className="bx bx-user" />,
  },
  cellPhone: {
    label: "Numero Celular",
    name: "cellPhone",
    type: "phone",
    required: true,
    icon: <i className="bx bx-mobile-alt" />,
  },
  idCard: {
    label: "Cedula titular",
    name: "holderIdCard",
    type: "cedula",
    required: true,
    icon: <i className="bx bx-id-card" />,
  },
  email: {
    label: "Correo electrónico",
    name: "email",
    type: "email",
    required: true,
    icon: <i className="bx bx-envelope" />,
  },
  address: {
    label: "Dirección",
    name: "address",
    type: "text",
    required: true,
    icon: <i className="bx bx-location-plus" />,
  },
  password: {
    label: "Contraseña",
    name: "password",
    type: "password",
    required: true,
    icon: <i className="bx bx-lock" />,
  },
  cardNumber: {
    label: "Numero tarjeta",
    name: "cardNumber",
    type: "creditCard",
    required: true,
    icon: <i className="bx bxs-credit-card" />,
  },
  expiryDate: {
    label: "Fecha de vencimiento",
    name: "expiryDate",
    type: "date",
    required: true,
    icon: <i className="bx bx-calendar" />,
  },
  SecurityCode: {
    label: "Codigo de seguridad",
    name: "SecurityCode",
    type: "number",
    required: true,
    icon: <i className="bx bx-lock" />,
  },
};
